/// Flutter icons StateIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  StateIcons
///      fonts:
///       - asset: fonts/StateIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class StateIcons {
  StateIcons._();

  static const _kFontFam = 'StateIcons';
  static const String? _kFontPkg = null;

  static const IconData alabama = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alaska = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData colorado = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arizona = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arkansas = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData california = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData connecticut = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deleware = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData florida = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData georgia = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
