import 'package:flutter/cupertino.dart';
import 'package:us_travel_checklist/util/state_icons_icons.dart';

const Map<String, bool> US_STATES = {
  "Alabama": false,
  "Alaska": false,
  "Arizona": false,
  "Arkansas": false,
  "California": false,
  "Colorado": false,
  "Connecticut": false,
  "Delaware": false,
  // "District Of Columbia": false,
  "Florida": false,
  "Georgia": false,
  // "Hawaii": false,
  // "Idaho": false,
  // "Illinois": false,
  // "Indiana": false,
  // "Iowa": false,
  // "Kansas": false,
  // "Kentucky": false,
  // "Louisiana": false,
  // "Maine": false,
  // "Maryland": false,
  // "Massachusetts": false,
  // "Michigan": false,
  // "Minnesota": false,
  // "Mississippi": false,
  // "Missouri": false,
  // "Montana": false,
  // "Nebraska": false,
  // "Nevada": false,
  // "New Hampshire": false,
  // "New Jersey": false,
  // "New Mexico": false,
  // "New York": false,
  // "North Carolina": false,
  // "North Dakota": false,
  // "Ohio": false,
  // "Oklahoma": false,
  // "Oregon": false,
  // "Pennsylvania": false,
  // "Rhode Island": false,
  // "South Carolina": false,
  // "South Dakota": false,
  // "Tennessee": false,
  // "Texas": false,
  // "Utah": false,
  // "Vermont": false,
  // "Virginia": false,
  // "Washington": false,
  // "West Virginia": false,
  // "Wisconsin": false,
  // "Wyoming": false
};

const Map<String, IconData> STATE_ICONS = {
  "Alabama": StateIcons.alabama,
  "Alaska": StateIcons.alaska,
  "Arizona": StateIcons.colorado,
  "Arkansas": StateIcons.arkansas,
  "California": StateIcons.california,
  "Colorado": StateIcons.colorado,
  "Connecticut": StateIcons.connecticut,
  "Delaware": StateIcons.deleware,
  // // "District Of Columbia": false,
  "Florida": StateIcons.florida,
  "Georgia": StateIcons.georgia,
  // "Hawaii": false,
  // "Idaho": false,
  // "Illinois": false,
  // "Indiana": false,
  // "Iowa": false,
  // "Kansas": false,
  // "Kentucky": false,
  // "Louisiana": false,
  // "Maine": false,
  // "Maryland": false,
  // "Massachusetts": false,
  // "Michigan": false,
  // "Minnesota": false,
  // "Mississippi": false,
  // "Missouri": false,
  // "Montana": false,
  // "Nebraska": false,
  // "Nevada": false,
  // "New Hampshire": false,
  // "New Jersey": false,
  // "New Mexico": false,
  // "New York": false,
  // "North Carolina": false,
  // "North Dakota": false,
  // "Ohio": false,
  // "Oklahoma": false,
  // "Oregon": false,
  // "Pennsylvania": false,
  // "Rhode Island": false,
  // "South Carolina": false,
  // "South Dakota": false,
  // "Tennessee": false,
  // "Texas": false,
  // "Utah": false,
  // "Vermont": false,
  // "Virginia": false,
  // "Washington": false,
  // "West Virginia": false,
  // "Wisconsin": false,
  // "Wyoming": false
};
