import 'package:flutter/cupertino.dart';
import 'package:us_travel_checklist/util/state_icons.dart';

const Map<String, bool> US_STATES = {
  "Alabama": false,
  "Alaska": false,
  "Arizona": false,
  "Arkansas": false,
  "California": false,
  "Colorado": false,
  "Connecticut": false,
  "Delaware": false,
  // "District Of Columbia": false,
  "Florida": false,
  "Georgia": false,
  "Hawaii": false,
  "Idaho": false,
  "Illinois": false,
  "Indiana": false,
  "Iowa": false,
  "Kansas": false,
  "Kentucky": false,
  "Louisiana": false,
  "Maine": false,
  "Maryland": false,
  "Massachusetts": false,
  "Michigan": false,
  "Minnesota": false,
  "Mississippi": false,
  "Missouri": false,
  "Montana": false,
  "Nebraska": false,
  "Nevada": false,
  "New Hampshire": false,
  "New Jersey": false,
  "New Mexico": false,
  "New York": false,
  "North Carolina": false,
  "North Dakota": false,
  "Ohio": false,
  "Oklahoma": false,
  "Oregon": false,
  "Pennsylvania": false,
  "Rhode Island": false,
  "South Carolina": false,
  "South Dakota": false,
  "Tennessee": false,
  "Texas": false,
  "Utah": false,
  "Vermont": false,
  "Virginia": false,
  "Washington": false,
  "West Virginia": false,
  "Wisconsin": false,
  "Wyoming": false
};

const Map<String, IconData> STATE_ICONS = {
  "Alabama": StateIcons.alabama,
  "Alaska": StateIcons.alaska,
  "Arizona": StateIcons.arizona,
  "Arkansas": StateIcons.arkansas,
  "California": StateIcons.california,
  "Colorado": StateIcons.colorado,
  "Connecticut": StateIcons.connecticut,
  "Delaware": StateIcons.deleware,
  // // "District Of Columbia": false,
  "Florida": StateIcons.florida,
  "Georgia": StateIcons.georgia,
  "Hawaii": StateIcons.hawaii,
  "Idaho": StateIcons.idaho,
  "Illinois": StateIcons.illinois,
  "Indiana": StateIcons.indiana,
  "Iowa": StateIcons.iowa,
  "Kansas": StateIcons.kansas,
  "Kentucky": StateIcons.kentucky,
  "Louisiana": StateIcons.louisiana,
  "Maine": StateIcons.maine,
  "Maryland": StateIcons.maryland,
  "Massachusetts": StateIcons.massachusetss,
  "Michigan": StateIcons.michigan,
  "Minnesota": StateIcons.minnesota,
  "Mississippi": StateIcons.mississippi,
  "Missouri": StateIcons.missouri,
  "Montana": StateIcons.montana,
  "Nebraska": StateIcons.nebraska,
  "Nevada": StateIcons.nevada,
  "New Hampshire": StateIcons.newHampshire,
  "New Jersey": StateIcons.newJersey,
  "New Mexico": StateIcons.newMexico,
  "New York": StateIcons.newYork,
  "North Carolina": StateIcons.northCarolina,
  "North Dakota": StateIcons.northDakota,
  "Ohio": StateIcons.ohio,
  "Oklahoma": StateIcons.oklahoma,
  "Oregon": StateIcons.oregon,
  "Pennsylvania": StateIcons.pennsylvania,
  "Rhode Island": StateIcons.rhodeIsland,
  "South Carolina": StateIcons.southCarolina,
  "South Dakota": StateIcons.southDakota,
  "Tennessee": StateIcons.tennessee,
  "Texas": StateIcons.texas,
  "Utah": StateIcons.utah,
  "Vermont": StateIcons.vermont,
  "Virginia": StateIcons.virginia,
  "Washington": StateIcons.washinton,
  "West Virginia": StateIcons.westVirginia,
  "Wisconsin": StateIcons.wisconsin,
  "Wyoming": StateIcons.wyoming,
};
